module.exports = {
  elements: [
    { name: "None" },
    {
      name: "Hydrogen",
      appearance: "colorless gas",
      atomic_mass: 1.008,
      boil: 20.271,
      category: "diatomic nonmetal",
      color: null,
      density: 0.08988,
      melt: 13.99,
      molar_heat: 28.836,
      number: 1,
      symbol: "H",
    },
    {
      name: "Helium",
      appearance: "colorless gas",
      atomic_mass: 4.0026022,
      boil: 4.222,
      category: "noble gas",
      color: null,
      density: 0.1786,
      melt: 0.95,
      molar_heat: null,
      number: 2,
      symbol: "He",
    },
    {
      name: "Lithium",
      appearance: "silvery-white",
      atomic_mass: 6.94,
      boil: 1603,
      category: "alkali metal",
      color: null,
      density: 0.534,
      melt: 453.65,
      molar_heat: 24.86,
      number: 3,
      symbol: "Li",
    },
    {
      name: "Beryllium",
      appearance: "white-gray metallic",
      atomic_mass: 9.01218315,
      boil: 2742,
      category: "alkaline earth metal",
      color: null,
      density: 1.85,
      melt: 1560,
      molar_heat: 16.443,
      number: 4,
      symbol: "Be",
    },
    {
      name: "Boron",
      appearance: "black-brown",
      atomic_mass: 10.81,
      boil: 4200,
      category: "metalloid",
      color: null,
      density: 2.08,
      melt: 2349,
      molar_heat: 11.087,
      number: 5,
      symbol: "B",
    },
    {
      name: "Carbon",
      appearance: null,
      atomic_mass: 12.011,
      boil: null,
      category: "polyatomic nonmetal",
      color: null,
      density: 1.821,
      melt: null,
      molar_heat: 8.517,
      number: 6,
      symbol: "C",
    },
    {
      name: "Nitrogen",
      appearance: "colorless gas, liquid or solid",
      atomic_mass: 14.007,
      boil: 77.355,
      category: "diatomic nonmetal",
      color: null,
      density: 1.251,
      melt: 63.15,
      molar_heat: null,
      number: 7,
      symbol: "N",
    },
    {
      name: "Oxygen",
      appearance: null,
      atomic_mass: 15.999,
      boil: 90.188,
      category: "diatomic nonmetal",
      color: null,
      density: 1.429,
      melt: 54.36,
      molar_heat: null,
      number: 8,
      symbol: "O",
    },
    {
      name: "Fluorine",
      appearance: null,
      atomic_mass: 18.9984031636,
      boil: 85.03,
      category: "diatomic nonmetal",
      color: null,
      density: 1.696,
      melt: 53.48,
      molar_heat: null,
      number: 9,
      symbol: "F",
    },
    {
      name: "Neon",
      appearance: "colorless gas",
      atomic_mass: 20.17976,
      boil: 27.104,
      category: "noble gas",
      color: null,
      density: 0.9002,
      melt: 24.56,
      molar_heat: null,
      number: 10,
      symbol: "Ne",
    },
    {
      name: "Sodium",
      appearance: "silvery white metallic",
      atomic_mass: 22.989769282,
      boil: 1156.09,
      category: "alkali metal",
      color: null,
      density: 0.968,
      melt: 370.944,
      molar_heat: 28.23,
      number: 11,
      symbol: "Na",
    },
    {
      name: "Magnesium",
      appearance: "shiny grey solid",
      atomic_mass: 24.305,
      boil: 1363,
      category: "alkaline earth metal",
      color: null,
      density: 1.738,
      melt: 923,
      molar_heat: 24.869,
      number: 12,
      symbol: "Mg",
    },
    {
      name: "Aluminium",
      appearance: "silvery gray metallic",
      atomic_mass: 26.98153857,
      boil: 2743,
      category: "post-transition metal",
      color: null,
      density: 2.7,
      melt: 933.47,
      molar_heat: 24.2,
      number: 13,
      symbol: "Al",
    },
    {
      name: "Silicon",
      appearance: null,
      atomic_mass: 28.085,
      boil: 3538,
      category: "metalloid",
      color: null,
      density: 2.329,
      melt: 1687,
      molar_heat: 19.789,
      number: 14,
      symbol: "Si",
    },
    {
      name: "Phosphorus",
      appearance: "colourless, yellow, scarlet, red, violet, black",
      atomic_mass: 30.9737619985,
      boil: null,
      category: "polyatomic nonmetal",
      color: null,
      density: 1.823,
      melt: null,
      molar_heat: 23.824,
      number: 15,
      symbol: "P",
    },
    {
      name: "Sulfur",
      appearance: "lemon yellow",
      atomic_mass: 32.06,
      boil: 717.8,
      category: "polyatomic nonmetal",
      color: null,
      density: 2.07,
      melt: 388.36,
      molar_heat: 22.75,
      number: 16,
      symbol: "S",
    },
    {
      name: "Chlorine",
      appearance: "pale yellow-green gas",
      atomic_mass: 35.45,
      boil: 239.11,
      category: "diatomic nonmetal",
      color: null,
      density: 3.2,
      melt: 171.6,
      molar_heat: null,
      number: 17,
      symbol: "Cl",
    },
    {
      name: "Argon",
      appearance: "colorless gas",
      atomic_mass: 39.9481,
      boil: 87.302,
      category: "noble gas",
      color: null,
      density: 1.784,
      melt: 83.81,
      molar_heat: null,
      number: 18,
      symbol: "Ar",
    },
    {
      name: "Potassium",
      appearance: "silvery gray",
      atomic_mass: 39.09831,
      boil: 1032,
      category: "alkali metal",
      color: null,
      density: 0.862,
      melt: 336.7,
      molar_heat: 29.6,
      number: 19,
      symbol: "K",
    },
    {
      name: "Calcium",
      appearance: null,
      atomic_mass: 40.0784,
      boil: 1757,
      category: "alkaline earth metal",
      color: null,
      density: 1.55,
      melt: 1115,
      molar_heat: 25.929,
      number: 20,
      symbol: "Ca",
    },
    {
      name: "Scandium",
      appearance: "silvery white",
      atomic_mass: 44.9559085,
      boil: 3109,
      category: "transition metal",
      color: null,
      density: 2.985,
      melt: 1814,
      molar_heat: 25.52,
      number: 21,
      symbol: "Sc",
    },
    {
      name: "Titanium",
      appearance: "silvery grey-white metallic",
      atomic_mass: 47.8671,
      boil: 3560,
      category: "transition metal",
      color: null,
      density: 4.506,
      melt: 1941,
      molar_heat: 25.06,
      number: 22,
      symbol: "Ti",
    },
    {
      name: "Vanadium",
      appearance: "blue-silver-grey metal",
      atomic_mass: 50.94151,
      boil: 3680,
      category: "transition metal",
      color: null,
      density: 6,
      melt: 2183,
      molar_heat: 24.89,
      number: 23,
      symbol: "V",
    },
    {
      name: "Chromium",
      appearance: "silvery metallic",
      atomic_mass: 51.99616,
      boil: 2944,
      category: "transition metal",
      color: null,
      density: 7.19,
      melt: 2180,
      molar_heat: 23.35,
      number: 24,
      symbol: "Cr",
    },
    {
      name: "Manganese",
      appearance: "silvery metallic",
      atomic_mass: 54.9380443,
      boil: 2334,
      category: "transition metal",
      color: null,
      density: 7.21,
      melt: 1519,
      molar_heat: 26.32,
      number: 25,
      symbol: "Mn",
    },
    {
      name: "Iron",
      appearance: "metallic grayish",
      atomic_mass: 55.8452,
      boil: 3134,
      category: "transition metal",
      color: null,
      density: 7.874,
      melt: 1811,
      molar_heat: 25.1,
      number: 26,
      symbol: "Fe",
    },
    {
      name: "Cobalt",
      appearance: "hard lustrous gray metal",
      atomic_mass: 58.9331944,
      boil: 3200,
      category: "transition metal",
      color: "metallic gray",
      density: 8.9,
      melt: 1768,
      molar_heat: 24.81,
      number: 27,
      symbol: "Co",
    },
    {
      name: "Nickel",
      appearance: "silver with a gold tinge",
      atomic_mass: 58.69344,
      boil: 3003,
      category: "transition metal",
      color: null,
      density: 8.908,
      melt: 1728,
      molar_heat: 26.07,
      number: 28,
      symbol: "Ni",
    },
    {
      name: "Copper",
      appearance: "red-orange metallic luster",
      atomic_mass: 63.5463,
      boil: 2835,
      category: "transition metal",
      color: null,
      density: 8.96,
      melt: 1357.77,
      molar_heat: 24.44,
      number: 29,
      symbol: "Cu",
    },
    {
      name: "Zinc",
      appearance: "silver-gray",
      atomic_mass: 65.382,
      boil: 1180,
      category: "transition metal",
      color: null,
      density: 7.14,
      melt: 692.68,
      molar_heat: 25.47,
      number: 30,
      symbol: "Zn",
    },
    {
      name: "Gallium",
      appearance: "silver-white",
      atomic_mass: 69.7231,
      boil: 2673,
      category: "post-transition metal",
      color: null,
      density: 5.91,
      melt: 302.9146,
      molar_heat: 25.86,
      number: 31,
      symbol: "Ga",
    },
    {
      name: "Germanium",
      appearance: "grayish-white",
      atomic_mass: 72.6308,
      boil: 3106,
      category: "metalloid",
      color: null,
      density: 5.323,
      melt: 1211.4,
      molar_heat: 23.222,
      number: 32,
      symbol: "Ge",
    },
    {
      name: "Arsenic",
      appearance: "metallic grey",
      atomic_mass: 74.9215956,
      boil: null,
      category: "metalloid",
      color: null,
      density: 5.727,
      melt: null,
      molar_heat: 24.64,
      number: 33,
      symbol: "As",
    },
    {
      name: "Selenium",
      appearance: "black, red",
      atomic_mass: 78.9718,
      boil: 958,
      category: "polyatomic nonmetal",
      color: null,
      density: 4.81,
      melt: 494,
      molar_heat: 25.363,
      number: 34,
      symbol: "Se",
    },
    {
      name: "Bromine",
      appearance: null,
      atomic_mass: 79.904,
      boil: 332,
      category: "diatomic nonmetal",
      color: null,
      density: 3.1028,
      melt: 265.8,
      molar_heat: null,
      number: 35,
      symbol: "Br",
    },
    {
      name: "Krypton",
      appearance: "colorless gas",
      atomic_mass: 83.7982,
      boil: 119.93,
      category: "noble gas",
      color: null,
      density: 3.749,
      melt: 115.78,
      molar_heat: null,
      number: 36,
      symbol: "Kr",
    },
    {
      name: "Rubidium",
      appearance: "grey white",
      atomic_mass: 85.46783,
      boil: 961,
      category: "alkali metal",
      color: null,
      density: 1.532,
      melt: 312.45,
      molar_heat: 31.06,
      number: 37,
      symbol: "Rb",
    },
    {
      name: "Strontium",
      appearance: null,
      atomic_mass: 87.621,
      boil: 1650,
      category: "alkaline earth metal",
      color: null,
      density: 2.64,
      melt: 1050,
      molar_heat: 26.4,
      number: 38,
      symbol: "Sr",
    },
    {
      name: "Yttrium",
      appearance: "silvery white",
      atomic_mass: 88.905842,
      boil: 3203,
      category: "transition metal",
      color: null,
      density: 4.472,
      melt: 1799,
      molar_heat: 26.53,
      number: 39,
      symbol: "Y",
    },
    {
      name: "Zirconium",
      appearance: "silvery white",
      atomic_mass: 91.2242,
      boil: 4650,
      category: "transition metal",
      color: null,
      density: 6.52,
      melt: 2128,
      molar_heat: 25.36,
      number: 40,
      symbol: "Zr",
    },
    {
      name: "Niobium",
      appearance: "gray metallic, bluish",
      atomic_mass: 92.906372,
      boil: 5017,
      category: "transition metal",
      color: null,
      density: 8.57,
      melt: 2750,
      molar_heat: 24.6,
      number: 41,
      symbol: "Nb",
    },
    {
      name: "Molybdenum",
      appearance: "gray metallic",
      atomic_mass: 95.951,
      boil: 4912,
      category: "transition metal",
      color: null,
      density: 10.28,
      melt: 2896,
      molar_heat: 24.06,
      number: 42,
      symbol: "Mo",
    },
    {
      name: "Technetium",
      appearance: "shiny gray metal",
      atomic_mass: 98,
      boil: 4538,
      category: "transition metal",
      color: null,
      density: 11,
      melt: 2430,
      molar_heat: 24.27,
      number: 43,
      symbol: "Tc",
    },
    {
      name: "Ruthenium",
      appearance: "silvery white metallic",
      atomic_mass: 101.072,
      boil: 4423,
      category: "transition metal",
      color: null,
      density: 12.45,
      melt: 2607,
      molar_heat: 24.06,
      number: 44,
      symbol: "Ru",
    },
    {
      name: "Rhodium",
      appearance: "silvery white metallic",
      atomic_mass: 102.905502,
      boil: 3968,
      category: "transition metal",
      color: null,
      density: 12.41,
      melt: 2237,
      molar_heat: 24.98,
      number: 45,
      symbol: "Rh",
    },
    {
      name: "Palladium",
      appearance: "silvery white",
      atomic_mass: 106.421,
      boil: 3236,
      category: "transition metal",
      color: null,
      density: 12.023,
      melt: 1828.05,
      molar_heat: 25.98,
      number: 46,
      symbol: "Pd",
    },
    {
      name: "Silver",
      appearance: "lustrous white metal",
      atomic_mass: 107.86822,
      boil: 2435,
      category: "transition metal",
      color: null,
      density: 10.49,
      melt: 1234.93,
      molar_heat: 25.35,
      number: 47,
      symbol: "Ag",
    },
    {
      name: "Cadmium",
      appearance: "silvery bluish-gray metallic",
      atomic_mass: 112.4144,
      boil: 1040,
      category: "transition metal",
      color: null,
      density: 8.65,
      melt: 594.22,
      molar_heat: 26.02,
      number: 48,
      symbol: "Cd",
    },
    {
      name: "Indium",
      appearance: "silvery lustrous gray",
      atomic_mass: 114.8181,
      boil: 2345,
      category: "post-transition metal",
      color: null,
      density: 7.31,
      melt: 429.7485,
      molar_heat: 26.74,
      number: 49,
      symbol: "In",
    },
    {
      name: "Tin",
      appearance: "silvery-white or gray",
      atomic_mass: 118.7107,
      boil: 2875,
      category: "post-transition metal",
      color: null,
      density: 7.365,
      melt: 505.08,
      molar_heat: 27.112,
      number: 50,
      symbol: "Sn",
    },
    {
      name: "Antimony",
      appearance: "silvery lustrous gray",
      atomic_mass: 121.7601,
      boil: 1908,
      category: "metalloid",
      color: null,
      density: 6.697,
      melt: 903.78,
      molar_heat: 25.23,
      number: 51,
      symbol: "Sb",
    },
    {
      name: "Tellurium",
      appearance: null,
      atomic_mass: 127.603,
      boil: 1261,
      category: "metalloid",
      color: null,
      density: 6.24,
      melt: 722.66,
      molar_heat: 25.73,
      number: 52,
      symbol: "Te",
    },
    {
      name: "Iodine",
      appearance: "lustrous metallic gray, violet as a gas",
      atomic_mass: 126.904473,
      boil: 457.4,
      category: "diatomic nonmetal",
      color: null,
      density: 4.933,
      melt: 386.85,
      molar_heat: null,
      number: 53,
      symbol: "I",
    },
    {
      name: "Xenon",
      appearance: "colorless gas",
      atomic_mass: 131.2936,
      boil: 165.051,
      category: "noble gas",
      color: null,
      density: 5.894,
      melt: 161.4,
      molar_heat: null,
      number: 54,
      symbol: "Xe",
    },
    {
      name: "Cesium",
      appearance: "silvery gold",
      atomic_mass: 132.905451966,
      boil: 944,
      category: "alkali metal",
      color: null,
      density: 1.93,
      melt: 301.7,
      molar_heat: 32.21,
      number: 55,
      symbol: "Cs",
    },
    {
      name: "Barium",
      appearance: null,
      atomic_mass: 137.3277,
      boil: 2118,
      category: "alkaline earth metal",
      color: null,
      density: 3.51,
      melt: 1000,
      molar_heat: 28.07,
      number: 56,
      symbol: "Ba",
    },
    {
      name: "Lanthanum",
      appearance: "silvery white",
      atomic_mass: 138.905477,
      boil: 3737,
      category: "lanthanide",
      color: null,
      density: 6.162,
      melt: 1193,
      molar_heat: 27.11,
      number: 57,
      symbol: "La",
    },
    {
      name: "Cerium",
      appearance: "silvery white",
      atomic_mass: 140.1161,
      boil: 3716,
      category: "lanthanide",
      color: null,
      density: 6.77,
      melt: 1068,
      molar_heat: 26.94,
      number: 58,
      symbol: "Ce",
    },
    {
      name: "Praseodymium",
      appearance: "grayish white",
      atomic_mass: 140.907662,
      boil: 3403,
      category: "lanthanide",
      color: null,
      density: 6.77,
      melt: 1208,
      molar_heat: 27.2,
      number: 59,
      symbol: "Pr",
    },
    {
      name: "Neodymium",
      appearance: "silvery white",
      atomic_mass: 144.2423,
      boil: 3347,
      category: "lanthanide",
      color: null,
      density: 7.01,
      melt: 1297,
      molar_heat: 27.45,
      number: 60,
      symbol: "Nd",
    },
    {
      name: "Promethium",
      appearance: "metallic",
      atomic_mass: 145,
      boil: 3273,
      category: "lanthanide",
      color: null,
      density: 7.26,
      melt: 1315,
      molar_heat: null,
      number: 61,
      symbol: "Pm",
    },
    {
      name: "Samarium",
      appearance: "silvery white",
      atomic_mass: 150.362,
      boil: 2173,
      category: "lanthanide",
      color: null,
      density: 7.52,
      melt: 1345,
      molar_heat: 29.54,
      number: 62,
      symbol: "Sm",
    },
    {
      name: "Europium",
      appearance: null,
      atomic_mass: 151.9641,
      boil: 1802,
      category: "lanthanide",
      color: null,
      density: 5.264,
      melt: 1099,
      molar_heat: 27.66,
      number: 63,
      symbol: "Eu",
    },
    {
      name: "Gadolinium",
      appearance: "silvery white",
      atomic_mass: 157.253,
      boil: 3273,
      category: "lanthanide",
      color: null,
      density: 7.9,
      melt: 1585,
      molar_heat: 37.03,
      number: 64,
      symbol: "Gd",
    },
    {
      name: "Terbium",
      appearance: "silvery white",
      atomic_mass: 158.925352,
      boil: 3396,
      category: "lanthanide",
      color: null,
      density: 8.23,
      melt: 1629,
      molar_heat: 28.91,
      number: 65,
      symbol: "Tb",
    },
    {
      name: "Dysprosium",
      appearance: "silvery white",
      atomic_mass: 162.5001,
      boil: 2840,
      category: "lanthanide",
      color: null,
      density: 8.54,
      melt: 1680,
      molar_heat: 27.7,
      number: 66,
      symbol: "Dy",
    },
    {
      name: "Holmium",
      appearance: "silvery white",
      atomic_mass: 164.930332,
      boil: 2873,
      category: "lanthanide",
      color: null,
      density: 8.79,
      melt: 1734,
      molar_heat: 27.15,
      number: 67,
      symbol: "Ho",
    },
    {
      name: "Erbium",
      appearance: "silvery white",
      atomic_mass: 167.2593,
      boil: 3141,
      category: "lanthanide",
      color: null,
      density: 9.066,
      melt: 1802,
      molar_heat: 28.12,
      number: 68,
      symbol: "Er",
    },
    {
      name: "Thulium",
      appearance: "silvery gray",
      atomic_mass: 168.934222,
      boil: 2223,
      category: "lanthanide",
      color: null,
      density: 9.32,
      melt: 1818,
      molar_heat: 27.03,
      number: 69,
      symbol: "Tm",
    },
    {
      name: "Ytterbium",
      appearance: null,
      atomic_mass: 173.0451,
      boil: 1469,
      category: "lanthanide",
      color: null,
      density: 6.9,
      melt: 1097,
      molar_heat: 26.74,
      number: 70,
      symbol: "Yb",
    },
    {
      name: "Lutetium",
      appearance: "silvery white",
      atomic_mass: 174.96681,
      boil: 3675,
      category: "lanthanide",
      color: null,
      density: 9.841,
      melt: 1925,
      molar_heat: 26.86,
      number: 71,
      symbol: "Lu",
    },
    {
      name: "Hafnium",
      appearance: "steel gray",
      atomic_mass: 178.492,
      boil: 4876,
      category: "transition metal",
      color: null,
      density: 13.31,
      melt: 2506,
      molar_heat: 25.73,
      number: 72,
      symbol: "Hf",
    },
    {
      name: "Tantalum",
      appearance: "gray blue",
      atomic_mass: 180.947882,
      boil: 5731,
      category: "transition metal",
      color: null,
      density: 16.69,
      melt: 3290,
      molar_heat: 25.36,
      number: 73,
      symbol: "Ta",
    },
    {
      name: "Tungsten",
      appearance: "grayish white, lustrous",
      atomic_mass: 183.841,
      boil: 6203,
      category: "transition metal",
      color: null,
      density: 19.25,
      melt: 3695,
      molar_heat: 24.27,
      number: 74,
      symbol: "W",
    },
    {
      name: "Rhenium",
      appearance: "silvery-grayish",
      atomic_mass: 186.2071,
      boil: 5869,
      category: "transition metal",
      color: null,
      density: 21.02,
      melt: 3459,
      molar_heat: 25.48,
      number: 75,
      symbol: "Re",
    },
    {
      name: "Osmium",
      appearance: "silvery, blue cast",
      atomic_mass: 190.233,
      boil: 5285,
      category: "transition metal",
      color: null,
      density: 22.59,
      melt: 3306,
      molar_heat: 24.7,
      number: 76,
      symbol: "Os",
    },
    {
      name: "Iridium",
      appearance: "silvery white",
      atomic_mass: 192.2173,
      boil: 4403,
      category: "transition metal",
      color: null,
      density: 22.56,
      melt: 2719,
      molar_heat: 25.1,
      number: 77,
      symbol: "Ir",
    },
    {
      name: "Platinum",
      appearance: "silvery white",
      atomic_mass: 195.0849,
      boil: 4098,
      category: "transition metal",
      color: null,
      density: 21.45,
      melt: 2041.4,
      molar_heat: 25.86,
      number: 78,
      symbol: "Pt",
    },
    {
      name: "Gold",
      appearance: "metallic yellow",
      atomic_mass: 196.9665695,
      boil: 3243,
      category: "transition metal",
      color: null,
      density: 19.3,
      melt: 1337.33,
      molar_heat: 25.418,
      number: 79,
      symbol: "Au",
    },
    {
      name: "Mercury",
      appearance: "silvery",
      atomic_mass: 200.5923,
      boil: 629.88,
      category: "transition metal",
      color: null,
      density: 13.534,
      melt: 234.321,
      molar_heat: 27.983,
      number: 80,
      symbol: "Hg",
    },
    {
      name: "Thallium",
      appearance: "silvery white",
      atomic_mass: 204.38,
      boil: 1746,
      category: "post-transition metal",
      color: null,
      density: 11.85,
      melt: 577,
      molar_heat: 26.32,
      number: 81,
      symbol: "Tl",
    },
    {
      name: "Lead",
      appearance: "metallic gray",
      atomic_mass: 207.21,
      boil: 2022,
      category: "post-transition metal",
      color: null,
      density: 11.34,
      melt: 600.61,
      molar_heat: 26.65,
      number: 82,
      symbol: "Pb",
    },
    {
      name: "Bismuth",
      appearance: "lustrous silver",
      atomic_mass: 208.980401,
      boil: 1837,
      category: "post-transition metal",
      color: null,
      density: 9.78,
      melt: 544.7,
      molar_heat: 25.52,
      number: 83,
      symbol: "Bi",
    },
    {
      name: "Polonium",
      appearance: "silvery",
      atomic_mass: 209,
      boil: 1235,
      category: "post-transition metal",
      color: null,
      density: 9.196,
      melt: 527,
      molar_heat: 26.4,
      number: 84,
      symbol: "Po",
    },
    {
      name: "Astatine",
      appearance: null,
      atomic_mass: 210,
      boil: 610,
      category: "metalloid",
      color: null,
      density: 6.35,
      melt: 575,
      molar_heat: null,
      number: 85,
      symbol: "At",
    },
    {
      name: "Radon",
      appearance: "colorless gas",
      atomic_mass: 222,
      boil: 211.5,
      category: "noble gas",
      color: null,
      density: 9.73,
      melt: 202,
      molar_heat: null,
      number: 86,
      symbol: "Rn",
    },
    {
      name: "Francium",
      appearance: null,
      atomic_mass: 223,
      boil: 950,
      category: "alkali metal",
      color: null,
      density: 1.87,
      melt: 300,
      molar_heat: null,
      number: 87,
      symbol: "Fr",
    },
    {
      name: "Radium",
      appearance: "silvery white metallic",
      atomic_mass: 226,
      boil: 2010,
      category: "alkaline earth metal",
      color: null,
      density: 5.5,
      melt: 1233,
      molar_heat: null,
      number: 88,
      symbol: "Ra",
    },
    {
      name: "Actinium",
      appearance: null,
      atomic_mass: 227,
      boil: 3500,
      category: "actinide",
      color: null,
      density: 10,
      melt: 1500,
      molar_heat: 27.2,
      number: 89,
      symbol: "Ac",
    },
    {
      name: "Thorium",
      appearance: "silvery, often with black tarnish",
      atomic_mass: 232.03774,
      boil: 5061,
      category: "actinide",
      color: null,
      density: 11.724,
      melt: 2023,
      molar_heat: 26.23,
      number: 90,
      symbol: "Th",
    },
    {
      name: "Protactinium",
      appearance: "bright, silvery metallic luster",
      atomic_mass: 231.035882,
      boil: 4300,
      category: "actinide",
      color: null,
      density: 15.37,
      melt: 1841,
      molar_heat: null,
      number: 91,
      symbol: "Pa",
    },
    {
      name: "Uranium",
      appearance: null,
      atomic_mass: 238.028913,
      boil: 4404,
      category: "actinide",
      color: null,
      density: 19.1,
      melt: 1405.3,
      molar_heat: 27.665,
      number: 92,
      symbol: "U",
    },
    {
      name: "Neptunium",
      appearance: "silvery metallic",
      atomic_mass: 237,
      boil: 4447,
      category: "actinide",
      color: null,
      density: 20.45,
      melt: 912,
      molar_heat: 29.46,
      number: 93,
      symbol: "Np",
    },
    {
      name: "Plutonium",
      appearance: "silvery white to dark gray",
      atomic_mass: 244,
      boil: 3505,
      category: "actinide",
      color: null,
      density: 19.816,
      melt: 912.5,
      molar_heat: 35.5,
      number: 94,
      symbol: "Pu",
    },
    {
      name: "Americium",
      appearance: "silvery white",
      atomic_mass: 243,
      boil: 2880,
      category: "actinide",
      color: null,
      density: 12,
      melt: 1449,
      molar_heat: 62.7,
      number: 95,
      symbol: "Am",
    },
    {
      name: "Curium",
      appearance: "silvery metallic, glows purple in the dark",
      atomic_mass: 247,
      boil: 3383,
      category: "actinide",
      color: null,
      density: 13.51,
      melt: 1613,
      molar_heat: null,
      number: 96,
      symbol: "Cm",
    },
    {
      name: "Berkelium",
      appearance: "silvery",
      atomic_mass: 247,
      boil: 2900,
      category: "actinide",
      color: null,
      density: 14.78,
      melt: 1259,
      molar_heat: null,
      number: 97,
      symbol: "Bk",
    },
    {
      name: "Californium",
      appearance: "silvery",
      atomic_mass: 251,
      boil: 1743,
      category: "actinide",
      color: null,
      density: 15.1,
      melt: 1173,
      molar_heat: null,
      number: 98,
      symbol: "Cf",
    },
    {
      name: "Einsteinium",
      appearance: "silver-colored",
      atomic_mass: 252,
      boil: 1269,
      category: "actinide",
      color: null,
      density: 8.84,
      melt: 1133,
      molar_heat: null,
      number: 99,
      symbol: "Es",
    },
    {
      name: "Fermium",
      appearance: null,
      atomic_mass: 257,
      boil: null,
      category: "actinide",
      color: null,
      density: null,
      melt: 1800,
      molar_heat: null,
      number: 100,
      symbol: "Fm",
    },
    {
      name: "Mendelevium",
      appearance: null,
      atomic_mass: 258,
      boil: null,
      category: "actinide",
      color: null,
      density: null,
      melt: 1100,
      molar_heat: null,
      number: 101,
      symbol: "Md",
    },
    {
      name: "Nobelium",
      appearance: null,
      atomic_mass: 259,
      boil: null,
      category: "actinide",
      color: null,
      density: null,
      melt: 1100,
      molar_heat: null,
      number: 102,
      symbol: "No",
    },
    {
      name: "Lawrencium",
      appearance: null,
      atomic_mass: 266,
      boil: null,
      category: "actinide",
      color: null,
      density: null,
      melt: 1900,
      molar_heat: null,
      number: 103,
      symbol: "Lr",
    },
    {
      name: "Rutherfordium",
      appearance: null,
      atomic_mass: 267,
      boil: 5800,
      category: "transition metal",
      color: null,
      density: 23.2,
      melt: 2400,
      molar_heat: null,
      number: 104,
      symbol: "Rf",
    },
    {
      name: "Dubnium",
      appearance: null,
      atomic_mass: 268,
      boil: null,
      category: "transition metal",
      color: null,
      density: 29.3,
      melt: null,
      molar_heat: null,
      number: 105,
      symbol: "Db",
    },
    {
      name: "Seaborgium",
      appearance: null,
      atomic_mass: 269,
      boil: null,
      category: "transition metal",
      color: null,
      density: 35,
      melt: null,
      molar_heat: null,
      number: 106,
      symbol: "Sg",
    },
    {
      name: "Bohrium",
      appearance: null,
      atomic_mass: 270,
      boil: null,
      category: "transition metal",
      color: null,
      density: 37.1,
      melt: null,
      molar_heat: null,
      number: 107,
      symbol: "Bh",
    },
    {
      name: "Hassium",
      appearance: null,
      atomic_mass: 269,
      boil: null,
      category: "transition metal",
      color: null,
      density: 40.7,
      melt: 126,
      molar_heat: null,
      number: 108,
      symbol: "Hs",
    },
    {
      name: "Meitnerium",
      appearance: null,
      atomic_mass: 278,
      boil: null,
      category: "unknown",
      color: null,
      density: 37.4,
      melt: null,
      molar_heat: null,
      number: 109,
      symbol: "Mt",
    },
    {
      name: "Darmstadtium",
      appearance: null,
      atomic_mass: 281,
      boil: null,
      category: "unknown",
      color: null,
      density: 34.8,
      melt: null,
      molar_heat: null,
      number: 110,
      symbol: "Ds",
    },
    {
      name: "Roentgenium",
      appearance: null,
      atomic_mass: 282,
      boil: null,
      category: "unknown",
      color: null,
      density: 28.7,
      melt: null,
      molar_heat: null,
      number: 111,
      symbol: "Rg",
    },
    {
      name: "Copernicium",
      appearance: null,
      atomic_mass: 285,
      boil: 3570,
      category: "transition metal",
      color: null,
      density: 23.7,
      melt: null,
      molar_heat: null,
      number: 112,
      symbol: "Cn",
    },
    {
      name: "Nihonium",
      appearance: null,
      atomic_mass: 286,
      boil: 1430,
      category: "unknown",
      color: null,
      density: 16,
      melt: 700,
      molar_heat: null,
      number: 113,
      symbol: "Nh",
    },
    {
      name: "Flerovium",
      appearance: null,
      atomic_mass: 289,
      boil: 420,
      category: "post-transition metal",
      color: null,
      density: 14,
      melt: 340,
      molar_heat: null,
      number: 114,
      symbol: "Fl",
    },
    {
      name: "Moscovium",
      appearance: null,
      atomic_mass: 289,
      boil: 1400,
      category: "unknown",
      color: null,
      density: 13.5,
      melt: 670,
      molar_heat: null,
      number: 115,
      symbol: "Mc",
    },
    {
      name: "Livermorium",
      appearance: null,
      atomic_mass: 293,
      boil: 1085,
      category: "unknown",
      color: null,
      density: 12.9,
      melt: 709,
      molar_heat: null,
      number: 116,
      symbol: "Lv",
    },
    {
      name: "Tennessine",
      appearance: null,
      atomic_mass: 294,
      boil: 883,
      category: "unknown",
      color: null,
      density: 7.17,
      melt: 723,
      molar_heat: null,
      number: 117,
      symbol: "Ts",
    },
    {
      name: "Oganesson",
      appearance: null,
      atomic_mass: 294,
      boil: 350,
      category: "unknown",
      color: null,
      density: 4.95,
      melt: null,
      molar_heat: null,
      number: 118,
      symbol: "Og",
    },
    {
      name: "Ununennium",
      appearance: null,
      atomic_mass: 315,
      boil: 630,
      category: "unknown",
      color: null,
      density: 3,
      melt: null,
      molar_heat: null,
      number: 119,
      symbol: "Uue",
    },
  ],
};
